name: Fetch Daily News

on:
  schedule:
    - cron: "0 17 * * *"  # 17:00 UTC daily
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # ✅ use your PAT here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python save_news.py

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add cached_articles.json
          git commit -m "📰 Daily update: $(date -u '+%Y-%m-%d')" || exit 0
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
